import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image' 
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Realestate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
    </div>
  )
}
